version: '30.2'
candidate_urls:
- https://raw.githubusercontent.com/freefq/free/master/v2
- https://raw.githubusercontent.com/mahdibland/V2RayAggregator/master/Eternity.txt
- https://raw.githubusercontent.com/mahdibland/V2RayAggregator/master/sub/splitted/trojan.txt
- https://raw.githubusercontent.com/ermaozi/get_subscribe/main/subscribe/v2ray.txt
- https://raw.githubusercontent.com/mahdibland/V2RayAggregator/master/sub/splitted/ss.txt
- https://raw.githubusercontent.com/mfuu/v2ray/master/v2ray
- https://raw.githubusercontent.com/mahdibland/V2RayAggregator/master/sub/splitted/vmess.txt
- https://raw.githubusercontent.com/peasoft/NoMoreWalls/master/list.txt
- https://raw.githubusercontent.com/Epodonios/v2ray-configs/main/Splitted-By-Protocol/vless.txt
- https://raw.githubusercontent.com/Pawdroid/Free-servers/main/sub
- https://raw.githubusercontent.com/Epodonios/v2ray-configs/main/Splitted-By-Protocol/vmess.txt
- https://raw.githubusercontent.com/barry-far/V2ray-Config/main/Splitted-By-Protocol/ss.txt
- https://raw.githubusercontent.com/Epodonios/v2ray-configs/main/Splitted-By-Protocol/trojan.txt
- https://raw.githubusercontent.com/Epodonios/v2ray-configs/main/All_Configs_Sub.txt
- https://raw.githubusercontent.com/barry-far/V2ray-Config/main/All_Configs_Sub.txt
- https://raw.githubusercontent.com/Epodonios/v2ray-configs/main/Splitted-By-Protocol/ss.txt
- https://raw.githubusercontent.com/barry-far/V2ray-Config/main/Splitted-By-Protocol/vmess.txt
- https://raw.githubusercontent.com/barry-far/V2ray-Config/main/Splitted-By-Protocol/trojan.txt
- https://raw.githubusercontent.com/barry-far/V2ray-Config/main/Splitted-By-Protocol/vless.txt
- https://shz.al/~WangCai
- https://raw.githubusercontent.com/ssrsub/ssr/master/v2ray
- https://raw.githubusercontent.com/ermaozi/get_subscribe/main/subscribe/clash.yml
- https://raw.githubusercontent.com/anaer/Sub/main/clash.yaml
- https://raw.githubusercontent.com/peasoft/NoMoreWalls/master/list.meta.yml
- https://raw.githubusercontent.com/mfuu/v2ray/master/clash.yaml
- https://raw.githubusercontent.com/free18/v2ray/refs/heads/main/v.txt
- https://raw.githubusercontent.com/free18/v2ray/refs/heads/main/c.yaml
- https://raw.githubusercontent.com/shaoyouvip/free/refs/heads/main/all.yaml
- https://raw.githubusercontent.com/MohammadBahemmat/V2ray-Collector/main/all_servers.txt
- https://raw.githubusercontent.com/R3ZARAHIMI/tg-v2ray-configs-every2h/main/Config_jo.txt
- https://raw.githubusercontent.com/R3ZARAHIMI/tg-v2ray-configs-every2h/main/Original-Config.txt
- https://raw.githubusercontent.com/longlon/v2ray-config/main/All_Configs_Sub.txt
- https://cdn.jsdelivr.net/gh/learnhard-cn/free_proxy_ss@main/clash/clash.provider.yaml
github_base_repos:
- ermaozi/get_subscribe
- peasoft/NoMoreWalls
- freefq/free
- mfuu/v2ray
- mahdibland/V2RayAggregator
- Pawdroid/Free-servers
- anaer/Sub
- Epodonios/v2ray-configs
- barry-far/V2ray-Config
- MohammadBahemmat/V2ray-Collector
- R3ZARAHIMI/tg-v2ray-configs-every2h
- longlon/v2ray-config
- ssrsub/ssr
- free18/v2ray
- shaoyouvip/free
telegram_channels:
- v2ray_free
- freev2rayng
- v2rayng_free
- sub_free
- vmessfree
- vlessfree
- trojanfree
- proxiesdaily
- clashnode
- freeclash
- freeproxy
- v2ray_share
- v2raydaily
- clashmeta
- mr_v2ray
- wxdy666
- dns68
- jriedian
- AlphaV2ray
- proxies_share
- freev2ray
- clashvpn
- v2rayngvpn
- freeVPNjd
- hysteria2_free
- SSR_V2Ray
- FreeNodeVPN
- proxy_node
- v2rayfree
- proxyfree
- clashfree
- v2ray_node
- free_node
- freevpnshare
- v2ray_ssr_free
- Configs_pool
- V2ray_Vpn_Free
- v2rayng_freeproxy
- clash_pro
- Proxy_Mirror
- Freenodeshare
- v2rayng_freeNode
- vpn_free2024
- Node_Collector
- clash_freenode
- SubscribePool
- VpnTehran
- free_server_vpn
- ShadowProxy66
- v2ray_shadow
- Config_collector_V2Ray
- VlessReality
- reality_vless
- v2ray_reality
- ProxyReality
- free_reality
- IranV2RAY
- V2RayTz
- hysteria2_proxy
- ProxyScrape_Free
- FreeV2rayX
- configs_hub
- vpnFreenode
- node_free_org
- SSToV2Ray
- V2RayNodeFree
